# Generated by Django 5.2.4 on 2025-07-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_rename_donor_name_donation_name_donation_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='payment_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card'), ('NetBanking', 'Net Banking')], max_length=20),
        ),
    ]
