# Generated by Django 5.2.4 on 2025-07-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_remove_userprofile_address_remove_userprofile_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emailid',
            field=models.EmailField(default='Anonymous', max_length=254),
            preserve_default=False,
        ),
    ]
