# Generated by Django 5.2.4 on 2025-07-25 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_user_delete_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='DonorProfile',
        ),
    ]
