# Generated by Django 5.2.4 on 2025-07-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='donor_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='donation',
            name='email',
            field=models.EmailField(default='dummy@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_type',
            field=models.CharField(default='Cash', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donation',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
